version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PLANNER_DB_PASSWORD: password
      PLANNER_DB_NAME: planner_db 
    ports:
      - "8080:3000"
    depends_on:
      - db
  db:
    image: postgres
    restart: unless-stopped 
    environment:
      POSTGRES_DB: planner_db
      POSTGRES_USER: planner
      POSTGRES_PASSWORD: password



