- hosts: all
  tasks:
  - community.docker.docker_login:
      username: vladves
      password: 48056197 
  
  - community.docker.docker_container:
      name: app
      image: "vladves/planner:{{ version }}"
      restart_policy: always
      state: started
      ports:
        - 3000:3000
      env:
        NODE_ENV: prodaction