- hosts: all
  become: true
  become_user: root
  tasks:
  - apt:
      name: docker.io 
      update_cache: yes
      cache_valid_time: 604800
  - apt:
      name: python3-pip
      update_cache: yes
      cache_valid_time: 604800

  - pip:
      name: docker