name: ci 
on:
  push:
    branches:
      - 'main'
env:
  TEST_TAG: ${{ secrets.DOCKER_USERNAME }}/planner:test
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup QEMU 
        uses: docker/setup-qemu-action@v3
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image 
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags:  ${{ env.TEST_TAG }}
      - name: TEST
        run: docker run --rm ${{ env.TEST_TAG }} make test
      - name: Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/planner:latest
