name: release
on:
  create:
    tags:
      - v*
env:
  APP_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/planner 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: docker pull ${{ env.APP_IMAGE_NAME }}:latest
      - run: docker tag ${{ env.APP_IMAGE_NAME }}:latest ${{ env.APP_IMAGE_NAME }}:${{ github.ref_name }}
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ${{ env.APP_IMAGE_NAME }}:${{ github.ref_name }}